### ISSUE TITLE
410 error "why we do what we do" image

### ISSUE THREAD

**Issue by ian-g** [met-office-lab/blog#232]
[see here] (https://github.com/met-office-lab/blog/blame/master/_posts/2015-08-07-why-we-do-what-we-do.md#L9)

**Comment by jacobtomlinson** [comment]
@ian-g cheers!

@niallrobinson yay I get to say "I told you so". Could you please move that image onto S3 and update the url.

**Comment by jacobtomlinson** [comment]
Fixed in b32130b54b52757fc8655c537195b687e171a862
