### ISSUE TITLE
Color of linked pages

### ISSUE THREAD

**Issue by AntoinedDMO** [met-office-lab/blog#304]
All the linked pages got the same color : purple. We could make a difference between pages that have been visited and the others, like on Wikipedia for example.

**Comment by jacobtomlinson** [comment]
This can be done quickly using the [a-variant mixin](https://github.com/met-office-lab/blog/blob/master/_sass/meto-informatics-lab/_mixins.scss#L22). We just need to add a [:visited selector](http://www.w3schools.com/cssref/sel_visited.asp) too with a different colour.

**Comment by AntoinedDMO** [comment]
Finally, it's better to let it like it is.
