### ISSUE TITLE
Home page video issue on mobile devices 

### ISSUE THREAD

**Issue by 05tb** [met-office-lab/blog#341]
The home page video will not automatically play on mobile devices as this features is prevented from working on them. As far as I am aware there is no work around for this, I might be wrong though.

I think the best way to fix this on the blog is to set a poster attribute to the video (http://www.w3schools.com/tags/att_video_poster.asp). This will show instead of the video on a mobile device. 

Possibly some device detection could be used as well to change what is displayed.

**Comment by 05tb** [comment]
You might also want to hide the video controls, so they don't show up when the video is loading

**Comment by jacobtomlinson** [comment]
Sounds good! Why don't you submit a PR for this?

**Comment by 05tb** [comment]
Fixed in pull request #342

**Comment by 05tb** [comment]
Fixed in #342
