### ISSUE TITLE
Individual team member pages show no images 

### ISSUE THREAD

**Issue by 05tb** [met-office-lab/blog#351]
Upon clicking the team members page their image does not load at the top of the page.
The reason for this is the image url is being appended to another url, see code below.
```
background-image: url(http://s3-eu-west-1.amazonaws.com/informatics-webimages/https://images.informaticslab.co.uk/profiles/cropped/alberto-arribas.png);
```
Feel like this is due to the removal of relative to a magic prefix image link method and swap to absolute urls in #348

**Comment by jacobtomlinson** [comment]
Done
